### ISSUE TITLE
Apart from pointing to outdated SDK, the link is broken, too

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/campaign.en#1]
Issue in ./help/v8/config/push-config.md

> As a Campaign administrator, you can download Campaign SDKs from the [Experience Cloud Software Distribution](https://experience.adobe.com/#/downloads/content/software-distributicampaign.html). For more information, contact [Adobe Customer Care](https://helpx.adobe.com/enterprise/admin-guide.html/enterprise/using/support-for-experience-cloud.ug.html).

The link to download Campaign SDK should read
[Experience Cloud Software Distribution](https://experience.adobe.com/#/downloads/content/software-distribution/en/campaign.html)

**Comment by Alicesnk** [comment]
Thanks for your feedback.  The issue has been resolved.
