### ISSUE TITLE
Link/relationship schema incorrectly specified

### ISSUE THREAD

**Issue by abhardwaj-dev** [AdobeDocs/campaign.en#3]
Issue in ./help/v8/dev/datamodel-best-practices.md

The documentation states "Define a link with a cardinality (1-N) in the schema on the (1) side. For example, the relation Recipient (1) – (N) Transaction should be defined in the transaction schema."

Based on the example and in practice this should be "Define a link with a cardinality (1-N) in the schema on the (**N**) side. For example, the relation Recipient (1) – (N) Transaction should be defined in the transaction schema."

**Comment by Alicesnk** [comment]
This update has been implemented. Thanks for your feedback!
