### ISSUE TITLE
Lastest release is 8.5.1, rather than 8.5. List of patches is missing NEO-49768 

### ISSUE THREAD

**Issue by dburwitz** [AdobeDocs/campaign.en#5]
Issue in ./help/v8/start/release-notes.md.
Please, clarify the full version number and build number of the lasted ACC v8 version being 8.5.1 (9525 - e5822de), 8.5.1 has been released on 30 June 2023. Predecessor was 8.4.5 (9482 - 7473736), released on 03 Apr 2023.

Also, List of patches is missing NEO-49768 BQ connector issue with Date time field

Evidence being versions of client console available to Campaign customer https://experience.adobe.com/#/downloads/content/software-distribution/en/campaign.html?1_group.propertyvalues.property=.%2Fjcr%3Acontent%2Fmetadata%2Fdc%3Aversion&1_group.propertyvalues.operation=equals&1_group.propertyvalues.0_values=target-version%3Acampaign%2F8&3_group.propertyvalues.property=.%2Fjcr%3Acontent%2Fmetadata%2Fdc%3AoperatingSystem&3_group.propertyvalues.operation=equals&3_group.propertyvalues.0_values=target-os%3Awindows&orderby=%40jcr%3Acontent%2Fmetadata%2Fdc%3Atitle&orderby.sort=desc&layout=list&p.offset=0&p.limit=2 are 8.5.1 and 8.4.5. But no 8.5.

**Comment by Alicesnk** [comment]
Hi @dburwitz, 
Thanks for your feedback. The version in the Release Notes is correct (8.5.1).
NEO-49768 affected v7.3. As a consequence, it is not mentioned in v8 release notes.
