### ISSUE TITLE
404 Errors on Referral Links

### ISSUE THREAD

**Issue by jtwood426** [AdobeDocs/campaign.en#6]
Issue in ./help/v8/connect/ac-ajo.md

The following links at the bottom of the page result in 404 errors

[Discover this integration in this end-to-end sample](https://experienceleague.adobe.com/en/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/using-adobe-campaign-classic#_blank).

[Learn more in Journey Optimizer documentation](https://experienceleague.adobe.com/en/docs/journey-optimizer/using/orchestrate-journeys/about-journey-building/using-adobe-campaign-classic#_blank).

**Comment by Alicesnk** [comment]
Thanks for your feedback @jtwood426 
This is now fixed. Changes will be live later today
Internal reference > DOCAC-10335
